### PR TITLE
Resolves issue #38

### PR DESCRIPTION
**Pull request by Tanyaverma3114**
Added a jewelry blog website.
@devvsakib please review and merge the pull request.

### CODE REVIEW

**Comment by devvsakib** [comment]
why you closed pull request? @Tanyaverma3114

**Comment by Tanyaverma3114** [comment]
1 check got failed, so, I didn't want to spam with unnecessary PR. I'm really sorry. I tried uploading another project but the same check failed.

**Comment by devvsakib** [comment]
> 1 check got failed, so, I didn't want to spam with unnecessary PR. I'm really sorry. I tried uploading another project but the same check failed.

this error doesnt matter. its just check  code.

**Comment by Tanyaverma3114** [comment]
Oh ohhkk...I didn't know about that as I'm new to it😅.
I'm reopening this PR. Can you please review and merge it?

**Review by devvsakib — APPROVED** [review]
nice,
just dont use var varibale

**Comment by devvsakib** [comment]
> Oh ohhkk...I didn't know about that as I'm new to it😅. I'm reopening this PR. Can you please review and merge it?

marged and hacktoberfest label added

**Comment by Tanyaverma3114** [comment]
Thank you

**Pull request merged**
