### PR TITLE
Solar Company Website

### PR DESCRIPTION
**Pull request by rajathnair**

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
i love this website, but for good practice, please add all images in an "image" folder after that, I will marge and label as hacktoberfest.

**Comment by rajathnair** [comment]
> i love this website, but for good practice, please add all images in an "image" folder after that, I will marge and label as hacktoberfest.

ok, I will close this pull request and will later upload it again

**Comment by devvsakib** [comment]
@rajathnair you dont need to close this, you can make change and pull request again😉

**Comment by rajathnair** [comment]
> @rajathnair you dont need to close this, you can make change and pull request again😉

can u just guide me how to do that ?

**Comment by devvsakib** [comment]
> > @rajathnair you dont need to close this, you can make change and pull request again😉
> 
> can u just guide me how to do that ?

just make change, and commit, then push. that's it

**Pull request closed without merging**
