### PR TITLE
Added my project called "Buildcon", a Builder Management System for the issue #11

### PR DESCRIPTION
**Pull request by deepanshu-sharmaa**

### CODE REVIEW

**Comment by deepanshu-sharmaa** [comment]
Made a PR for the issue #11 by adding my project called "BuildCon", a Builder Management System.

**Comment by deepanshu-sharmaa** [comment]
@devvsakib please merge this.

**Review by devvsakib — APPROVED** [review]

**Comment by devvsakib** [comment]
it would be helpful if join with us https://discord.gg/xwRbDwnbMr

**Comment by deepanshu-sharmaa** [comment]
Joined bro!

**Pull request merged**
